//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckListMaker.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CheckListMaker.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   help pages に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string About_Label_Help {
            get {
                return ResourceManager.GetString("About_Label_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   App Information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AppShell_Label_AppinfoText {
            get {
                return ResourceManager.GetString("AppShell_Label_AppinfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AppShell_Label_SettingsText {
            get {
                return ResourceManager.GetString("AppShell_Label_SettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Button_Text_Add {
            get {
                return ResourceManager.GetString("Button_Text_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Camera に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Button_Text_Camera {
            get {
                return ResourceManager.GetString("Button_Text_Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Histroy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Button_Text_Histroy {
            get {
                return ResourceManager.GetString("Button_Text_Histroy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Button_Text_Image {
            get {
                return ResourceManager.GetString("Button_Text_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not retrieve the list. Please run it again after a while or try another photo. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Exception_NoCheckItems {
            get {
                return ResourceManager.GetString("Exception_NoCheckItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enable the following permissions and run again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Exception_NoPermissions {
            get {
                return ResourceManager.GetString("Exception_NoPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Camera に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Exception_NoPermissions_Camera {
            get {
                return ResourceManager.GetString("Exception_NoPermissions_Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Media に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Exception_NoPermissions_Media {
            get {
                return ResourceManager.GetString("Exception_NoPermissions_Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add item に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Main_Entry_Placeholder {
            get {
                return ResourceManager.GetString("Main_Entry_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2 columns に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Main_Label_Switch {
            get {
                return ResourceManager.GetString("Main_Label_Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Completed! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Main_Snackbar_Done {
            get {
                return ResourceManager.GetString("Main_Snackbar_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Item deleted に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Main_String_DeleteMessage {
            get {
                return ResourceManager.GetString("Main_String_DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *Performance may be degraded. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Settings_Label_Annotation1 {
            get {
                return ResourceManager.GetString("Settings_Label_Annotation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dark mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Settings_Label_IsDark {
            get {
                return ResourceManager.GetString("Settings_Label_IsDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save previous state に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Settings_Label_Save {
            get {
                return ResourceManager.GetString("Settings_Label_Save", resourceCulture);
            }
        }
    }
}
