//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckListMaker.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CheckListMaker.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   help pages に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string About_Label_Help {
            get {
                return ResourceManager.GetString("About_Label_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddItemPopup_Entry_Placeholder {
            get {
                return ResourceManager.GetString("AddItemPopup_Entry_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add a check item に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddItemPopup_Label_AddTitle {
            get {
                return ResourceManager.GetString("AddItemPopup_Label_AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddItemPopup_Label_CloseButton {
            get {
                return ResourceManager.GetString("AddItemPopup_Label_CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Item deleted に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Alert_DeleteResultMessage {
            get {
                return ResourceManager.GetString("Alert_DeleteResultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The title has been updated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Alert_EditResultMessage {
            get {
                return ResourceManager.GetString("Alert_EditResultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirmation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Alert_Label_ConfirmTitle {
            get {
                return ResourceManager.GetString("Alert_Label_ConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to delete it? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Alert_Label_DeleteMessage {
            get {
                return ResourceManager.GetString("Alert_Label_DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit title. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Alert_Text_EditMessage {
            get {
                return ResourceManager.GetString("Alert_Text_EditMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Alert_Text_EditTitle {
            get {
                return ResourceManager.GetString("Alert_Text_EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Swipe each checklist to the right to display the edit and delete buttons. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Alert_Text_HelpMessage1 {
            get {
                return ResourceManager.GetString("Alert_Text_HelpMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can edit the checklist title using the edit button. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Alert_Text_HelpMessage2 {
            get {
                return ResourceManager.GetString("Alert_Text_HelpMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   How to edit checklists に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Alert_Text_HelpTitle {
            get {
                return ResourceManager.GetString("Alert_Text_HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   App Information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AppShell_Label_AppinfoText {
            get {
                return ResourceManager.GetString("AppShell_Label_AppinfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AppShell_Label_SettingsText {
            get {
                return ResourceManager.GetString("AppShell_Label_SettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Button_Text_Add {
            get {
                return ResourceManager.GetString("Button_Text_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Camera に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Button_Text_Camera {
            get {
                return ResourceManager.GetString("Button_Text_Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Button_Text_Delete {
            get {
                return ResourceManager.GetString("Button_Text_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit Title に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Button_Text_EditTitle {
            get {
                return ResourceManager.GetString("Button_Text_EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Histroy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Button_Text_Histroy {
            get {
                return ResourceManager.GetString("Button_Text_Histroy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Button_Text_Image {
            get {
                return ResourceManager.GetString("Button_Text_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CheckList_Text_Title {
            get {
                return ResourceManager.GetString("CheckList_Text_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not retrieve the list. Please run it again after a while or try another photo. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Exception_NoCheckItems {
            get {
                return ResourceManager.GetString("Exception_NoCheckItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enable the following permissions and run again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Exception_NoPermissions {
            get {
                return ResourceManager.GetString("Exception_NoPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Camera に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Exception_NoPermissions_Camera {
            get {
                return ResourceManager.GetString("Exception_NoPermissions_Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Media に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Exception_NoPermissions_Media {
            get {
                return ResourceManager.GetString("Exception_NoPermissions_Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0:MMM dd, yyyy (ddd) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Format_Date {
            get {
                return ResourceManager.GetString("Format_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   History に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string History_Title {
            get {
                return ResourceManager.GetString("History_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2 columns に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Main_Label_Switch {
            get {
                return ResourceManager.GetString("Main_Label_Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Completed! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Main_Snackbar_Done {
            get {
                return ResourceManager.GetString("Main_Snackbar_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Item deleted に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Main_String_DeleteMessage {
            get {
                return ResourceManager.GetString("Main_String_DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *Performance may be degraded. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Settings_Label_Annotation1 {
            get {
                return ResourceManager.GetString("Settings_Label_Annotation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dark mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Settings_Label_IsDark {
            get {
                return ResourceManager.GetString("Settings_Label_IsDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save previous state に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Settings_Label_Save {
            get {
                return ResourceManager.GetString("Settings_Label_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete checklist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Toolbar_Label_Delete {
            get {
                return ResourceManager.GetString("Toolbar_Label_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New checklist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Toolbar_Label_NewCheckList {
            get {
                return ResourceManager.GetString("Toolbar_Label_NewCheckList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Switch display に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Toolbar_Label_SwitchDisplay {
            get {
                return ResourceManager.GetString("Toolbar_Label_SwitchDisplay", resourceCulture);
            }
        }
    }
}
